export const ENV_PROXY = 'BBT_PROXY';
export const ENV_OPEN_AI_API_KEY = 'BBT_OPEN_AI_API_KEY';
export const ENV_OPEN_AI_BASE_URL = 'BBT_OPEN_AI_BASE_URL';
export const ENV_DEEPL_API_KEY = 'BBT_DEEPL_API_KEY';
export const ENV_DEEPL_BASE_URL = 'BBT_DEEPL_BASE_URL';
export const ENV_GOOGLE_API_KEY = 'BBT_GOOGLE_API_KEY';
export const ENV_GOOGLE_BASE_URL = 'BBT_GOOGLE_BASE_URL';
